openapi: 3.0.3
info:
  title: Juegocartas API
  version: 1.0.0
  description: >-
    Especificación OpenAPI mínima para el backend de Juegocartas.
    Incluye los endpoints principales usados por el cliente Next.js (partidas, jugar cartas, transformaciones).
servers:
  - url: http://localhost:8080
    description: Local development server
paths:
  /api/partidas/{codigo}:
    get:
      summary: Obtener resumen de una partida
      parameters:
        - name: codigo
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Resumen de la partida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PartidaSummary'
        '404':
          description: Partida no encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /api/partidas/{codigo}/jugar:
    post:
      summary: Jugar una carta en la partida
      parameters:
        - name: codigo
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/JugarCartaRequest'
      responses:
        '200':
          description: Resultado de la jugada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JugadaResult'
        '400':
          description: Petición inválida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /api/partidas/{codigo}/transformaciones/activar:
    post:
      summary: Activar una transformación para un jugador en la partida
      parameters:
        - name: codigo
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ActivarTransformacionRequest'
      responses:
        '200':
          description: Transformación activada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransformacionResponse'
        '400':
          description: Petición inválida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Partida o jugador no encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /api/partidas/{codigo}/transformaciones/desactivar:
    post:
      summary: Desactivar la transformación activa de un jugador
      parameters:
        - name: codigo
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DesactivarTransformacionRequest'
      responses:
        '200':
          description: Transformación desactivada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransformacionResponse'
        '400':
          description: Petición inválida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    PartidaSummary:
      type: object
      properties:
        codigo:
          type: string
        estado:
          type: string
          description: Estado de la partida (p. ej. WAITING, IN_PROGRESS, FINISHED)
        jugadores:
          type: array
          items:
            $ref: '#/components/schemas/JugadorSummary'
        cartasRestantes:
          type: integer
    JugadorSummary:
      type: object
      properties:
        id:
          type: string
        nombre:
          type: string
        puntos:
          type: integer
        transformacionActiva:
          type: boolean
    JugarCartaRequest:
      type: object
      required:
        - jugadorId
        - cartaId
      properties:
        jugadorId:
          type: string
          description: Id del jugador que juega la carta
        cartaId:
          type: string
          description: Id de la carta que se juega
        atributoSeleccionado:
          type: string
          description: Atributo elegido para la comparación (por ejemplo "ki", "fuerza")
    JugadaResult:
      type: object
      properties:
        ganadorId:
          type: string
        detalles:
          type: string
    ActivarTransformacionRequest:
      type: object
      required:
        - jugadorId
        - indiceTransformacion
      properties:
        jugadorId:
          type: string
          description: Id del jugador que activa la transformación
        indiceTransformacion:
          type: integer
          description: Índice (0-based) de la transformación disponible en la carta del jugador
    DesactivarTransformacionRequest:
      type: object
      required:
        - jugadorId
      properties:
        jugadorId:
          type: string
          description: Id del jugador que desactiva la transformación
    TransformacionResponse:
      type: object
      properties:
        jugadorId:
          type: string
        indice:
          type: integer
        nombre:
          type: string
        multiplicador:
          type: number
          format: double
        activa:
          type: boolean
    ErrorResponse:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
        status:
          type: integer
        error:
          type: string
        message:
          type: string
        path:
          type: string
security: []
