/* tslint:disable */
/* eslint-disable */
/**
 * Juegocartas API
 * Especificación OpenAPI mínima para el backend de Juegocartas. Incluye los endpoints principales usados por el cliente Next.js (partidas, jugar cartas, transformaciones).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

